/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ms.graha.b2.freeswim1;
import processing.core.*;

public class App extends PApplet{
	public void settings() {
		size(500, 500);
	}

	public void draw(){
		background(64);
		ellipse(mouseX, mouseY, 20, 20);
	}
  
	public static void main(String[] passedArgs) {
		String[] appletArgs = new String[] { "ms.graha.b2.freeswim1.App" };
		PApplet.main(appletArgs);
    }
}
